/**
 * Generates `src/fonts/index.ts` — the one module the layout imports fonts from.
 *
 * The licensed faces (Swift, Acid Grotesk) are not redistributable, so the
 * woff2 files are gitignored and a fresh clone does not have them. But
 * `next/font/local` fails the build when a file is missing — it is a
 * compile-time API. So this script, run from postinstall/prebuild/predev,
 * writes one of two modules:
 *
 * - fonts present  → the real next/font/local registration (self-hosted,
 *   preloaded, exactly the wiring the production site uses), or
 * - fonts absent   → a stub that registers nothing. The font-family tokens in
 *   tokens.css carry native fallback stacks inside their var() defaults, so
 *   the dashboard renders on the best serif/grotesk each platform ships.
 *
 * Drop licensed woff2 files into src/fonts/ and rebuild to switch up; the
 * module is regenerated on every install/build/dev, never edited by hand.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const FONTS = join(HERE, "..", "src", "fonts");
const OUT = join(FONTS, "index.ts");

const files = [
  "swift-regular.woff2",
  "swift-bold.woff2",
  "acid-grotesk-regular.woff2",
  "acid-grotesk-medium.woff2",
];
const present = files.filter((f) => existsSync(join(FONTS, f)));
const licensed = present.length === files.length;

const header = `/**
 * GENERATED by scripts/setup-fonts.mjs — do not edit; it is rewritten on
 * every install, build, and dev run. See that script for why this exists.
 */
`;

const licensedModule = `${header}
import localFont from "next/font/local";

const swift = localFont({
  src: [
    { path: "./swift-regular.woff2", weight: "400", style: "normal" },
    { path: "./swift-bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-swift",
  display: "block",
  fallback: ["Georgia", "Times New Roman", "serif"],
});

const acid = localFont({
  src: [
    { path: "./acid-grotesk-regular.woff2", weight: "400", style: "normal" },
    { path: "./acid-grotesk-medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-acid",
  display: "block",
  fallback: ["Helvetica Neue", "Arial", "sans-serif"],
});

/** Class list for <html>: registers the licensed faces via CSS variables. */
export const fontClasses = \`\${swift.variable} \${acid.variable}\`;
`;

const fallbackModule = `${header}
/**
 * Licensed font files were not present at build time, so nothing is
 * registered: --font-swift / --font-acid stay unset and the var() defaults
 * in src/styles/tokens.css supply the native stacks.
 */
export const fontClasses = "";
`;

const next = licensed ? licensedModule : fallbackModule;
const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : null;
if (current !== next) {
  writeFileSync(OUT, next);
  console.log(
    licensed
      ? "fonts: licensed faces found — using next/font (Swift, Acid Grotesk)"
      : `fonts: licensed faces not found (${present.length}/${files.length}) — using native fallback stacks`,
  );
}
